In [1]:
import nibabel as nib

In [2]:
vista_res = nib.load('/Users/aditya/Documents/GitHub/prf-mapping/temp/December 2023/Vista/original_jc_fit/RF_ss5-fFit.nii.gz')

In [3]:
vista_res

In [5]:
vista_data = vista_res.get_fdata()

In [6]:
vista_data

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [8]:
vista_data

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [31]:
nii = nib.load('/Users/aditya/Documents/GitHub/prf-mapping/sample_data/JC/RF1/JC_RF1_vista/bar_seq_1_ss5.nii.gz')

In [32]:
nii.shape

(128, 128, 128, 201)

In [33]:
data = nii.get_fdata()

In [34]:
import numpy as np

In [39]:
data_first_frame = data[:, :, :, 0]

In [40]:
num_voxels_greater_than_zero_first_frame = np.sum(data_first_frame > 0)

In [41]:
num_voxels_greater_than_zero_first_frame

119083

In [35]:
average_data = np.mean(data, axis=3)

In [36]:
num_voxels_greater_than_zero = np.sum(average_data > 0)

In [37]:
print(num_voxels_greater_than_zero)

119083


In [21]:
nii = nib.load('/Users/aditya/Documents/GitHub/prf-mapping/sample_data/JC/RF1/JC_RF1_vista/bar_seq_1_ss5.nii.gz')
dat = nii.get_fdata()

In [22]:
mask = nib.load('/Users/aditya/Documents/GitHub/prf-mapping/sample_data/JC/surfanat_brainmask_master.nii.gz').get_fdata() != 0

In [23]:
[xi,yi,zi] = np.nonzero(mask)

In [24]:
indices = [(xi[i],yi[i],zi[i]) for i in range(len(xi))]

In [25]:
bold_psc = dat[mask]

In [26]:
bold_psc

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
bold_psc.shape

(218854, 201)

In [43]:
voxel_variances = np.var(bold_psc, axis=1)

In [44]:
num_voxels_nonzero_variance = np.sum(voxel_variances > 0)

In [45]:
num_voxels_nonzero_variance

119082